name: Build binaries

env:
  IMAGE_NAME: weather-station-sensor
  REGISTRY_USER: JulianSauer
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

on: [ push ]
jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - name: Build binaries
        run: GOOS=linux GOARCH=amd64 go build -o artifacts/weather-station-linux
      - run: GOOS=windows GOARCH=amd64 go build -o artifacts/weather-station-windows
      - run: GOOS=darwin GOARCH=amd64 go build -o artifacts/weather-station-darwin
      - run: GOOS=linux GOARCH=arm go build -o artifacts/weather-station-arm
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: weather-station-artifacts
          path: artifacts/

      - name: Build image
        run: docker build --tag $IMAGE_NAME .
      - name: Log into registry
        run: docker login docker.pkg.github.com --username "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker tag $IMAGE_NAME $IMAGE_ID:$GITHUB_SHA
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:$GITHUB_SHA
